const historiasDeIntercambio = {
  "alegria-tiempo": "Usaste un poco de tiempo para hacer algo que te gusta.",
  "alegria-dinero": "Compraste algo que te alegró el día.",
  "alegria-salud": "Sacrificas un poco tu cuerpo para mejorar tu estado de ánimo.",
  "alegria-determinacion": "Cambiaste una actividad productiva por una que te divierte.",
  "alegria-apoyo": "Te burlaste de alguien para divertirte, pero eso te hizo perder su apoyo.",
  "tiempo-alegria": "Renunciaste a una actividad divertida para ahorrar tiempo.",
  "tiempo-dinero": "Hiciste un gasto que te ayudará a tener más tiempo libre.",
  "tiempo-salud": "Dormiste menos para tener más tiempo para realizar una actividad.",
  "tiempo-determinacion": "Dejaste de hacer algunas de tus actividades para recuperar tiempo.",
  "tiempo-apoyo": "Preferiste ocuparte solo de tus cosas, y eso te distanció un poco de los demás.",
  "dinero-alegria": "Vendiste algo que te gustaba para conseguir dinero.",
  "dinero-tiempo": "Ayudaste en casa y recibiste algo de dinero por tu tiempo.",
  "dinero-salud": "Descuidaste tu salud para ganar dinero: dormiste menos y comiste rápido por trabajar de más.",
  "dinero-determinacion": "Preferiste una entrada económica, aunque descuidaste tus propias metas.",
  "dinero-apoyo": "Cobraste por ayudar a alguien que esperaba tu apoyo desinteresado.",
  "salud-alegria": "Te abstuviste de comer cosas ricas o darte gustos para sentirte físicamente mejor.",
  "salud-tiempo": "Dedicaste tiempo a meditar o dormir temprano para sentirte mejor.",
  "salud-dinero": "Gastaste dinero en atención médica para sentirte mejor.",
  "salud-determinacion": "Te sentiste bien físicamente después de hacer ejercicio, pero dejaste de lado tus metas personales.",
  "salud-apoyo": "Te enfocas en ti aunque eso te aleje de algunas personas.",
  "determinacion-alegria": "Renunciaste a un momento divertido para concentrarte en tus objetivos.",
  "determinacion-tiempo": "Te tomaste un tiempo para motivarte y volver a enfocarte.",
  "determinacion-dinero": "Pagaste un curso, taller o terapia que te ayudó a recuperar tus ganas de salir adelante.",
  "determinacion-salud": "Te forzaste más allá de tu límite físico.",
  "determinacion-apoyo": "Te enfocas en ganar sin preocuparte cómo afecta eso a los demás.",
  "apoyo-alegria": "Ayudaste a un amigo haciendo algo que no te gusta, pero eso fortaleció su apoyo hacia ti.",
  "apoyo-tiempo": "Ayudaste a alguien, usando parte de tu tiempo.",
  "apoyo-dinero": "Pagaste por ayuda profesional cuando lo necesitabas.",
  "apoyo-salud": "Cuidaste de alguien más, aunque afectó tu salud.",
  "apoyo-determinacion": "Apoyaste a un amigo en algo que iba contra tus principios, y eso te quitó determinación."
};
