let personajes = [
  {
    personajeID: 1,
    rutaImagen: "bonnelv",
    determinacion: 5,
    alegria: 15,
    apoyo: 10,
    salud: 13,
    dinero: 7,
    tiempo: 15,
  },
  {
    personajeID: 2,
    rutaImagen: "shanik",
    determinacion: 10,
    alegria: 10,
    apoyo: 7,
    salud: 6,
    dinero: 5,
    tiempo: 10,
  },
  {
    personajeID: 3,
    rutaImagen: "mferis",
    determinacion: 7,
    alegria: 11,
    apoyo: 8,
    salud: 13,
    dinero: 5,
    tiempo: 12,
  },
  {
    personajeID: 4,
    rutaImagen: "yeye",
    determinacion: 10,
    alegria: 9,
    apoyo: 10,
    salud: 9,
    dinero: 7,
    tiempo: 9,
  },
  {
    personajeID: 5,
    rutaImagen: "kzenteno",
    determinacion: 8,
    alegria: 11,
    apoyo: 12,
    salud: 12,
    dinero: 7,
    tiempo: 13,
  },
  {
    personajeID: 6,
    rutaImagen: "jmora",
    determinacion: 5,
    alegria: 13,
    apoyo: 6,
    salud: 13,
    dinero: 5,
    tiempo: 13,
  },
  {
    personajeID: 7,
    rutaImagen: "jazzbeltran",
    determinacion: 4,
    alegria: 8,
    apoyo: 6,
    salud: 13,
    dinero: 5,
    tiempo: 15,
  },
  {
    personajeID: 8,
    rutaImagen: "danfer",
    determinacion: 10,
    alegria: 10,
    apoyo: 8,
    salud: 11,
    dinero: 7,
    tiempo: 11,
  },
  {
    personajeID: 10,
    rutaImagen: "danilara",
    determinacion: 6,
    alegria: 12,
    apoyo: 7,
    salud: 13,
    dinero: 7,
    tiempo: 15,
  },
  {
    personajeID: 11,
    rutaImagen: "adrianflores",
    determinacion: 10,
    alegria: 13,
    apoyo: 12,
    salud: 9,
    dinero: 7,
    tiempo: 13,
  },
  {
    personajeID: 12,
    rutaImagen: "chokiskater",
    determinacion: 8,
    alegria: 9,
    apoyo: 8,
    salud: 12,
    dinero: 5,
    tiempo: 13,
  },
  {
    personajeID: 13,
    rutaImagen: "chrizdiaz",
    determinacion: 8,
    alegria: 10,
    apoyo: 8,
    salud: 12,
    dinero: 5,
    tiempo: 11,
  },
  {
    personajeID: 14,
    rutaImagen: "geresco",
    determinacion: 10,
    alegria: 8,
    apoyo: 10,
    salud: 9,
    dinero: 7,
    tiempo: 11,
  },
  {
    personajeID: 15,
    rutaImagen: "goguin",
    determinacion: 10,
    alegria: 11,
    apoyo: 10,
    salud: 12,
    dinero: 5,
    tiempo: 9,
  },
  {
    personajeID: 16,
    rutaImagen: "layun",
    determinacion: 6,
    alegria: 15,
    apoyo: 8,
    salud: 12,
    dinero: 7,
    tiempo: 11,
  },
  {
    personajeID: 17,
    rutaImagen: "omarap",
    determinacion: 10,
    alegria: 9,
    apoyo: 8,
    salud: 9,
    dinero: 5,
    tiempo: 13,
  },
  {
    personajeID: 18,
    rutaImagen: "pedroleon",
    determinacion: 10,
    alegria: 10,
    apoyo: 8,
    salud: 12,
    dinero: 7,
    tiempo: 11,
  },
  {
    personajeID: 19,
    rutaImagen: "willuri",
    determinacion: 8,
    alegria: 13,
    apoyo: 7,
    salud: 9,
    dinero: 5,
    tiempo: 15,
  },
];
